# -*- coding: utf-8 -*-
"""ai_gun2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uwru3PkhWPm-ICSal2rK6A1Pn4BDZxR6
"""



pip install   ultralytics

pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="bWz657SX9DiOSBruJ6Pp")
project = rf.workspace("eyantra-noxhw").project("eyantra-mgemz")
dataset = project.version(2).download("yolov8")

!yolo task = detect mode = train model = yolov8m.pt data = /content/eyantra-2/data.yaml epochs = 50 imgsz = 640

!yolo task=detect mode=predict model= /content/runs/detect/train3/weights/best.pt conf = 0.5 source = /content/eyantra-2/test/images/Quick-Camera-Image-2024-02-04-at-10-21-19-AM_png.rf.82254628d4c0d5bf1dfb1ba197c51871.jpg

from google.colab import drive
drive.mount('/content/drive')